Traceback (most recent call last):
  File "/home/cehrett/.conda/envs/jupyter-book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/cehrett/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/cehrett/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/cehrett/.conda/envs/jupyter-book/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/cehrett/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/cehrett/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/cehrett/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy, faiss, torch
print("NumPy", numpy.__version__)
print("FAISS", faiss.__version__, "(CPU) | Torch", torch.__version__, "CUDA", torch.version.cuda, "GPU", torch.cuda.is_available())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnumpy[39;00m[38;5;241m,[39m[38;5;250m [39m[38;5;21;01mfaiss[39;00m[38;5;241m,[39m[38;5;250m [39m[38;5;21;01mtorch[39;00m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mNumPy[39m[38;5;124m"[39m, numpy[38;5;241m.[39m__version__)
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mFAISS[39m[38;5;124m"[39m, faiss[38;5;241m.[39m__version__, [38;5;124m"[39m[38;5;124m(CPU) | Torch[39m[38;5;124m"[39m, torch[38;5;241m.[39m__version__, [38;5;124m"[39m[38;5;124mCUDA[39m[38;5;124m"[39m, torch[38;5;241m.[39mversion[38;5;241m.[39mcuda, [38;5;124m"[39m[38;5;124mGPU[39m[38;5;124m"[39m, torch[38;5;241m.[39mcuda[38;5;241m.[39mis_available())

[0;31mModuleNotFoundError[0m: No module named 'faiss'

